name: "Go Container Action Template"
description: "Get started with Go Container actions"
author: "Trent Rosenbaum"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
