name: Approval
on:
  pull_request_review:
    types:
    - submitted
    - edited
    - dismissed
jobs:
  reviews:
    runs-on: 'ubuntu-latest'
    outputs:
      output_num_approved: ${{ steps.reviews.outputs.approved }}
      output_num_changes_requested: ${{ steps.reviews.outputs.changes_requested }}
    steps:
      - id: 'get_reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
  approval:
    runs-on: 'ubuntu-latest'
    needs: reviews
    steps:
      - env:
          OUTPUT_NUM_APPROVED: ${{ needs.reviews.outputs.output_num_approved }}
          OUTPUT_NUM_CHARGES_REQUIRED: ${{ needs.reviews.outputs.output_num_changes_requested }}
        id: 'confirm_approval'
        if: 'OUTPUT_NUM_APPROVED => 1 && OUTPUT_NUM_CHARGES_REQUIRED == 0'
        run: echo "This PR has been approved"
