name: Approval
on:
  pull_request_review:
    types:
    - submitted
    - edited
    - dismissed
jobs:
  reviews-and-approve:
    runs-on: 'ubuntu-latest'
    steps:
      - name: get_reviews
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: approval
        if: steps.get_reviews.outputs.approved >= 1 && steps.get_reviews.outputs.changes_requested == 0
        run: echo "This PR has been approved!"
