name: Approval
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  count:
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'reviews'
        uses: 'anorkus/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
    outputs:
      approved_reviews: ${{ steps.reviews.outputs.approved }}
      changes_requested: ${{ steps.reviews.outputs.changes_requested }}

  confirm:
    runs-on: 'ubuntu-latest'
    needs:
      - count
    if: |
      always() && 
      needs.count.outputs.approved_reviews >= 1 && 
      needs.count.outputs.changes_requested == 0
    steps:
      - run: echo "This PR has been approved!"