name: Approve
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'reviews'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
      - if: 'steps.reviews.outputs.approved >= 1 && steps.reviews.outputs.changes_requested == 0'
        id: 'approve'
        run: echo "This PR has been approved!"