name: Approval
on:
  pull_request_review:
    types:
    - submitted
    - edited
    - dismissed
jobs:
  approved:
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'approved'
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
        if: 'steps.reviews.outputs.approved >= 1 && steps.reviews.outputs.changes_requested == 0'
        run: echo "This PR was approved!!!!"
