name: Integration Test
on:
  push:
  pull_request_review:
    types: [ submitted, edited, dismissed ]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: trentrosenbaum/go-container-action@main
        with:
          myInput: Golang

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello Golang"
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved!!!"
