name: Test
on:
  push:
jobs:
  integrations_test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Self test
        id: selftest
        # Put your action repo here
        uses: trentrosenbaum/go-container-action@main
        with:
          myInput: Golang
      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello Golang"
